const $ = s => document.querySelector(s);
const safe = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user, register=false, stream, config, currentOrders=[], trackingId, map, marker, watchId=null, sharingOrder=null, refreshPending=false, refreshQueued=false;
const label = s => s.replaceAll('_',' ');
const active = o => ['assigned','arriving','picked_up','in_transit'].includes(o.status);
const showMessage = s => { $('#message').textContent=s; };
const workspaces={customer:'/app',partner:'/partner',business:'/business',restaurant:'/restaurant',admin:'/operations'};
function renderNavigation(){const nav=$('header nav');nav.innerHTML=user?`<a href="/">Home</a><a href="${workspaces[user.role]}" aria-current="page">My workspace</a><a href="#support">Help & support</a>`:`<a href="/">Home</a><a href="/login"${!register?' aria-current="page"':''}>Sign in</a><a href="/signup"${register?' aria-current="page"':''}>Create account</a>`;}
function setAuthMode(create,changeUrl=true){register=create;$('#authTitle').textContent=register?'Create your account':'Welcome back';$('#authSubmit').textContent=register?'Create account':'Sign in';$('#authToggle').textContent=register?'Already have an account? Sign in':'Create an account';$('#nameLabel').hidden=!register;$('#roleLabel').hidden=!register;$('#nameLabel input').required=register;$('#authForm [name="password"]').autocomplete=register?'new-password':'current-password';if(changeUrl)history.replaceState(null,'',(register?'/signup':'/login')+location.search);renderNavigation();}
async function api(route,data) { const r=await fetch(`/api${route}`,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined}); const b=await r.json(); if(!r.ok)throw new Error(b.error);return b; }
function navigation(address) { return `https://www.google.com/maps/dir/?${new URLSearchParams({api:'1',destination:address,travelmode:'driving',dir_action:'navigate'})}`; }
function orderCard(o,role) {
  const next={assigned:'arriving',arriving:'picked_up',picked_up:'in_transit',in_transit:'completed'}[o.status];
  let actions=`<button data-track="${safe(o.id)}">View tracking</button>`;
  if(role==='partner') { if(next)actions+=`<button class="primary" data-status="${next}" data-id="${safe(o.id)}">${safe(label(next))}</button>`; if(active(o)){actions+=`<a class="button" target="_blank" rel="noopener" href="${safe(navigation(['assigned','arriving'].includes(o.status)?o.pickup:o.destination))}">Google navigation ↗</a><button data-share="${safe(o.id)}">${sharingOrder===o.id?'Stop sharing':'Share live location'}</button>`;} }
  if(role==='customer'&&o.status==='requested')actions+=`<button data-status="cancelled" data-id="${safe(o.id)}">Cancel request</button>`;
  if(role==='admin'&&['requested','assigned','arriving'].includes(o.status))actions+=`<button data-assign="${safe(o.id)}">Assign partner</button>`;
  return `<article class="order"><span class="badge">${safe(label(o.status))}</span><h3>${safe(label(o.service))}</h3><small>${safe(o.id)} · ${safe(new Date(o.created).toLocaleString())}</small><p><b>Pickup:</b> ${safe(o.pickup)}</p><p><b>Drop-off:</b> ${safe(o.destination)}</p><p>${safe(o.details?.note)}</p>${o.partner?`<p><b>Partner:</b> ${safe(o.partner.name)}</p>`:''}<div class="actions">${actions}</div></article>`;
}
function renderOrders(target,orders,role) { $(target).innerHTML=orders.length?orders.map(o=>orderCard(o,role)).join(''):'<div class="empty">Your next move will appear here.</div>'; }
async function refresh() {
  if(!user)return;if(refreshPending){refreshQueued=true;return;}refreshPending=true;
  try {
    const [orders,tickets]=await Promise.all([api('/orders'),api('/tickets')]);currentOrders=orders.orders;
    if(sharingOrder&&!currentOrders.some(o=>o.id===sharingOrder&&active(o)))stopSharing();
    if(user.role==='partner'){const [offers,me]=await Promise.all([api('/offers'),api('/me')]);user=me.user;$('#approval').textContent=user.approved?'Your account is approved. Accept a request to get moving.':'Operations approval is pending. Jobs become available after review.';renderOrders('#partnerOrders',currentOrders,'partner');$('#offers').innerHTML=offers.orders.length?offers.orders.map(o=>`<article class="order"><span class="badge">${safe(o.service)}</span><h3>${safe(o.pickup)} → ${safe(o.destination)}</h3><button class="primary" data-accept="${safe(o.id)}">Accept request</button></article>`).join(''):'<div class="empty">No available requests right now.</div>';}
    else if(user.role==='admin'){renderOrders('#adminOrders',currentOrders,'admin');$('#stats').innerHTML=`<div><b>${currentOrders.length}</b><span>Recent requests</span></div><div><b>${currentOrders.filter(active).length}</b><span>Active jobs</span></div><div><b>${currentOrders.filter(o=>o.status==='completed').length}</b><span>Completed</span></div>`;const partners=await api('/admin/partners');$('#partners').innerHTML=partners.partners.length?partners.partners.map(p=>`<article class="order"><h3>${safe(p.name)}</h3><p>${safe(p.email)}</p><span class="badge">${p.approved?'Approved':'Pending / suspended'}</span><div class="actions"><button data-approve="${safe(p.id)}" data-value="${!p.approved}">${p.approved?'Suspend':'Approve'}</button></div></article>`).join(''):'<div class="empty">New partner registrations appear here.</div>';}
    else renderOrders('#orders',currentOrders,'customer');
    $('#tickets').innerHTML=tickets.tickets.map(t=>`<article class="ticket"><span class="badge">${safe(t.status)}</span><h3>${safe(t.subject)}</h3><p>${safe(t.message)}</p>${user.role==='admin'&&t.status==='open'?`<button data-resolve="${safe(t.id)}">Mark resolved</button>`:''}</article>`).join('');
    if(trackingId)renderTracking(currentOrders.find(o=>o.id===trackingId));
  }catch(e){showMessage(e.message);}finally{refreshPending=false;if(refreshQueued){refreshQueued=false;queueMicrotask(refresh);}}
}
function stopSharing(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;sharingOrder=null;}
function shareLocation(id){if(sharingOrder===id){stopSharing();refresh();return;}if(!navigator.geolocation)throw new Error('Location is unavailable on this device.');stopSharing();sharingOrder=id;let last=0;watchId=navigator.geolocation.watchPosition(async({coords})=>{if(Date.now()-last<4000)return;last=Date.now();try{await api(`/orders/${encodeURIComponent(id)}/location`,{lat:coords.latitude,lng:coords.longitude,accuracy:coords.accuracy});showMessage('Sharing live location for this job. Keep this screen open.');}catch(e){stopSharing();showMessage(e.message);}},e=>{stopSharing();showMessage(`Location sharing stopped: ${e.message}`);refresh();},{enableHighAccuracy:true,maximumAge:5000,timeout:20000});refresh();}
async function renderTracking(o){if(!o)return;$('#trackingTitle').textContent=o.id;$('#trackingDetails').innerHTML=`<span class="badge">${safe(label(o.status))}</span><p>${safe(o.pickup)} → ${safe(o.destination)}</p>${o.partner?`<p>Partner: ${safe(o.partner.name)}</p>`:'<p>Waiting for a partner to accept.</p>'}`;$('#timeline').innerHTML=o.events.map(e=>`<div>${safe(label(e.status))}<small>${safe(new Date(e.created).toLocaleString())}</small></div>`).join('');const loc=o.location;$('#mapNote').textContent=loc?`Last location: ${new Date(loc.updated).toLocaleTimeString()} · accuracy ±${Math.round(loc.accuracy)} m${Date.now()-Date.parse(loc.updated)>30000?' · Location is stale; waiting for an update.':''}`:'The partner’s location appears after they explicitly start sharing for this job.';if(loc&&!config.mapsKey){$('#mapNote').textContent+=' The embedded map requires a Google Maps browser key.';$('#googleMap').style.display='none';return;}if(!loc){$('#googleMap').style.display='none';return;}try{await loadMaps();$('#googleMap').style.display='block';const position={lat:loc.lat,lng:loc.lng};if(!map){map=new google.maps.Map($('#googleMap'),{center:position,zoom:15});marker=new google.maps.Marker({position,map,title:'Delivery partner'});}else{marker.setPosition(position);map.setCenter(position);}}catch(e){$('#mapNote').textContent+=' Map could not load.';}}
let mapsPromise;
function loadMaps(){if(!mapsPromise)mapsPromise=new Promise((resolve,reject)=>{window.goServeMapsReady=resolve;const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(config.mapsKey)}&callback=goServeMapsReady&loading=async`;s.onerror=reject;document.head.append(s);});return mapsPromise;}
async function enter(){user=(await api('/me')).user;config=await api('/config');history.replaceState(null,'',workspaces[user.role]+location.search);renderNavigation();$('#auth').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#roleBadge').textContent=label(user.role).toUpperCase();$('#greeting').textContent=`Hello, ${user.name.split(' ')[0]}.`;
  $('#customerArea').hidden=!['customer','business'].includes(user.role);$('#partnerArea').hidden=user.role!=='partner';$('#adminArea').hidden=user.role!=='admin';$('#restaurantArea').hidden=user.role!=='restaurant';await refresh();stream?.close();stream=new EventSource('/api/stream');stream.addEventListener('refresh',refresh);stream.addEventListener('ready',()=>$('#connection').textContent='Connected · live updates');stream.onerror=()=>{$('#connection').textContent='Reconnecting…';};}
$('#authToggle').onclick=()=>setAuthMode(!register);
$('#authForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const button=$('#authSubmit');button.disabled=true;try{if(register)await api('/auth/register',data);await api('/auth/login',{email:data.email,password:data.password});showMessage('');await enter();}catch(error){showMessage(error.message);}finally{button.disabled=false;}};
let bookingAttempt;
$('#bookingForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const payload=Object.fromEntries(new FormData(e.target));const signature=JSON.stringify(payload);if(bookingAttempt?.signature!==signature)bookingAttempt={signature,id:crypto.randomUUID()};try{await api('/orders',{...payload,requestId:bookingAttempt.id});bookingAttempt=null;e.target.reset();showMessage('Request created. You can follow its status below.');await refresh();}catch(error){showMessage(error.message);}finally{button.disabled=false;}};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.resolve){await api('/admin/tickets',{id:b.dataset.resolve,status:'resolved'});await refresh();}if(b.dataset.assign){const {partners}=await api('/admin/partners');const approved=partners.filter(p=>p.approved);if(!approved.length)throw new Error('Approve a partner before assigning this request.');const modal=document.createElement('dialog');modal.innerHTML=`<h2>Assign an approved partner</h2><form><label>Partner<select name="partnerId">${approved.map(p=>`<option value="${safe(p.id)}">${safe(p.name)} · ${safe(p.email)}</option>`).join('')}</select></label><div class="actions"><button class="primary">Assign</button><button type="button" data-close>Cancel</button></div><p role="status"></p></form>`;document.body.append(modal);modal.querySelector('[data-close]').onclick=()=>modal.close();modal.addEventListener('close',()=>modal.remove());modal.querySelector('form').onsubmit=async event=>{event.preventDefault();try{await api('/admin/assign',{orderId:b.dataset.assign,partnerId:new FormData(event.target).get('partnerId')});modal.close();await refresh();}catch(error){modal.querySelector('[role="status"]').textContent=error.message;}};modal.showModal();}}catch(error){showMessage(error.message);}});
$('#supportForm').onsubmit=async e=>{e.preventDefault();try{await api('/tickets',Object.fromEntries(new FormData(e.target)));e.target.reset();showMessage('Support request saved.');await refresh();}catch(error){showMessage(error.message);}};
$('#logout').onclick=async()=>{try{await api('/auth/logout',{});stopSharing();stream?.close();location.href='/login';}catch(e){showMessage(e.message);}};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.accept)await api(`/orders/${encodeURIComponent(b.dataset.accept)}/accept`,{});else if(b.dataset.status)await api(`/orders/${encodeURIComponent(b.dataset.id)}/status`,{status:b.dataset.status});else if(b.dataset.approve)await api('/admin/partners',{id:b.dataset.approve,approved:b.dataset.value==='true'});else if(b.dataset.share){shareLocation(b.dataset.share);return;}else if(b.dataset.track){trackingId=b.dataset.track;await renderTracking(currentOrders.find(o=>o.id===trackingId));$('#tracking').showModal();return;}else return;await refresh();}catch(error){showMessage(error.message);}});
$('#closeTracking').onclick=()=>$('#tracking').close();$('#tracking').addEventListener('close',()=>{trackingId=null;});
document.querySelectorAll('nav a').forEach(a=>{if(a.getAttribute('href')===location.pathname)a.setAttribute('aria-current','page');});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
window.addEventListener('beforeunload',stopSharing);
setInterval(()=>{if(user&&document.visibilityState==='visible')refresh();},30000);
const selectedService=new URLSearchParams(location.search).get('service');
if(['food','ride','package','vehicle','business'].includes(selectedService))$('#bookingForm select').value=selectedService;
setAuthMode(location.pathname==='/signup',false);
enter().then(async()=>{const requested=new URLSearchParams(location.search).get('tracking');if(requested){const order=currentOrders.find(o=>o.id===requested);if(order){trackingId=requested;await renderTracking(order);$('#tracking').showModal();}else showMessage('That tracking number is not in your account.');}}).catch(error=>{setAuthMode(register);if(error.message!=='Please sign in.')showMessage(error.message);});
